USE S_NAV;

-- NEEDS A BETTER SOLUTION BUT ONLY RUN ONCE

-- CAMPUS INSERTION
INSERT INTO CAMPUS VALUES ('TRAFALGAR'), ('DAVIS'), ('HMC');

-- TRAFALGAR WING INSERTION
INSERT INTO WING VALUES ('A-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('AA-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('AS-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('B-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('C-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('D-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('DAYCARE', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('E-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('G-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('H-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('J-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('Elder Research Centre', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('TRANSPORTATION', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('ATHLETICS CENTRE', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('S-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));
INSERT INTO WING VALUES ('STUDENT-CENTRE', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'));

-- DAVIS WING INSERTION
INSERT INTO WING VALUES ('A-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('B-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('C-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('DAYCARE', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('H-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('J-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('M-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('M PORTABLES', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('TRANSPORTATION', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));
INSERT INTO WING VALUES ('STUDENT CENTRE', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'DAVIS'));

-- HMC WING INSERTION
INSERT INTO WING VALUES ('A-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'HMC'));
INSERT INTO WING VALUES ('B-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'HMC'));
INSERT INTO WING VALUES ('C-WING', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'HMC'));
INSERT INTO WING VALUES ('TRANSPORTATION', (SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'HMC'));

-- FLOOR INSERTION (TRAF S-WING) (ARGUABLE IF IT SHOULD BE IN DATABASE OR ACCESSIBLE ON SERVER)
INSERT INTO FLOOR_LEVEL VALUES (1,
(SELECT WING_ID FROM WING WHERE WING_ID = 
	(SELECT WING_ID FROM WING WHERE WING_NAME = 'S-WING' AND CAMPUS_ID = 
		(SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'))));

INSERT INTO FLOOR_LEVEL VALUES (2,
(SELECT WING_ID FROM WING WHERE WING_ID = 
	(SELECT WING_ID FROM WING WHERE WING_NAME = 'S-WING' AND CAMPUS_ID = 
		(SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'))));

INSERT INTO FLOOR_LEVEL VALUES (3,
(SELECT WING_ID FROM WING WHERE WING_ID = 
	(SELECT WING_ID FROM WING WHERE WING_NAME = 'S-WING' AND CAMPUS_ID = 
		(SELECT CAMPUS_ID FROM CAMPUS WHERE CAMPUS_NAME = 'TRAFALGAR'))));

EXEC InsertRoom 'S-WING', 201, '',2; 
EXEC InsertRoom 'S-WING', 202, '',2; 
EXEC InsertRoom 'S-WING', 202, 'A',2;
EXEC InsertRoom 'S-WING', 202, 'B',2; 
EXEC InsertRoom 'S-WING', 202, 'C',2; 
EXEC InsertRoom 'S-WING', 202, 'D',2;
EXEC InsertRoom 'S-WING', 203,'',2; 
EXEC InsertRoom 'S-WING', 204,'',2;
EXEC InsertRoom 'S-WING', 205,'',2; 
EXEC InsertRoom 'S-WING', 206,'',2;
EXEC InsertRoom 'S-WING', 206, 'A',2; 
EXEC InsertRoom 'S-WING', 206, 'B',2; 
EXEC InsertRoom 'S-WING', 207,'',2; 
EXEC InsertRoom 'S-WING', 207, 'A',2; 